### ISSUE TITLE
Unflatten does not work with pytorch 1.6

### ISSUE THREAD

**Issue by kaufManu** [naver/roma#2]
Thanks for this very useful library!

I'm getting an error in `internal.unflatten_batch_dims`:

```commandline
  File "site-packages\roma\mappings.py", line 397, in rotvec_to_rotmat
    return roma.internal.unflatten_batch_dims(R, batch_shape)
  File "site-packages\roma\internal.py", line 33, in unflatten_batch_dims
    return tensor.unflatten(dim=0, sizes=batch_shape) if len(batch_shape) > 0 else tensor.squeeze(0)
TypeError: unflatten() got an unexpected keyword argument 'sizes'
```

I think this happens because I'm using pytorch 1.6, which does not yet support this API. I'm not entirely sure when this change was introduced, but with pytorch 1.10 it's not a problem anymore. This fix might be as easy as bumping the pytorch version number in `requirements.txt` :)

**Comment by rbregier** [comment]
Hi, 
Thank you for reporting this bug !
It should be fixed with the latest commit (v1.2.7), could you please try it?
```
pip install git+https://github.com/naver/roma
```
I will update the PIP package and documentation afterwards.

**Comment by kaufManu** [comment]
Thanks for the quick reply! I confirm that this works with v1.2.7.

**Comment by rbregier** [comment]
Great, thanks for the feedback.
